spring:
  application:
    name: techmate_be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techmate}
    username: ${DB_USERNAME:stef}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 2
      pool-name: TechmateHikariCP

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.datasource: TRACE
    org.springframework.security: TRACE

jwt:
  key: ${JWT_SECRET_KEY}
  access_expiration: 3600000
  refresh_expiration: 604800000
  issuer: techmate

oauth:
  redirect_uri: ${OAUTH_REDIRECT_URI:http://localhost:4200/login}
  github:
    client_id: ${GITHUB_CLIENT_ID}
    client_secret: ${GITHUB_CLIENT_SECRET}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}

frontend:
  base_url: ${FRONTEND_URL:http://localhost:4200}